version: 0.2

phases:
  pre_build:
    commands:
      - echo Install dev dependencies
      - pip3 install flake8 black pytest pytest-astropy pytest-cov
      - pip3 install pytest pytest-astropy pytest-cov
      - pip3 install aws-cdk-lib==2.31.1 constructs==10.0.127
      
      - npm install -g aws-cdk
      - echo Lint with Black
      - black --check --diff app.py cdk_deployment
      - echo Lint with Flake
      - flake8 --count --max-line-length 88 app.py cdk_deployment
      - echo CDK Test
      - cdk synth
    
  build:
    commands:
      - echo Build completed on `date`
      - echo Deploying Pipeline Architecture...
      - cdk bootstrap -y --require-approval never
      - cdk deploy -y --require-approval never