# AWS Deployment Region
# Region that the pipeline will be deployed to
DEPLOYMENT_REGION: us-east-1

# Mission Name
# This is the name of the mission that will be used to dynamically create the instrument buckets
MISSION_NAME: hermes

# Package Name for Mission 
# This is the name of the package of the core package for the mission
MISSION_PKG: hermes_core

# Valid Data Levels
# This is a list of the valid data levels for the mission
VALID_DATA_LEVELS:
- l0
- l1
- ql 

# Instrument Names Used in the Mission. 
# The names are used to dynamically create the instrument bucket
INSTR_NAMES: 
- eea
- nemisis
- merit
- spani

# S3 Instrument Bucket Name
# The names of the buckets that will be created for the mission
INCOMING_BUCKET_NAME: swsoc-incoming

# S3 Sorting Lambda Bucket Name
# The name of the bucket that will be created to store the build artifacts for the sorting lambda
SORTING_LAMBDA_BUCKET_NAME: swsoc-sorting-lambda

# S3 Server Access Logs Bucket
# The name of the bucket that will be created to store the s3 server access logs
S3_SERVER_ACCESS_LOGS_BUCKET_NAME: swsoc-s3-server-access-logs

# Processing Lambda ECR Repository Name
# The name of the ECR repository that will be created to store the processing lambda image
PROCESSING_LAMBDA_PRIVATE_ECR_NAME: sdc_aws_processing_lambda

# Docker Base ECR Repository Name
# The name of the ECR repository that will be created to store the docker base image
DOCKER_BASE_PUBLIC_ECR_NAME: swsoc-docker-lambda-base

# Timestream Database and Table Names for Logs
# The names of the timestream database and table that will be created to store logs
TIMESTREAM_DATABASE_NAME: sdc_aws_logs
TIMESTREAM_S3_LOGS_TABLE_NAME: sdc_aws_s3_bucket_log_table
